name: pytest

on:
  pull_request:
    paths:
        - "**.py"
        - "uv.lock"
        - ".python-version"
        - "pyproject.toml"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5
    
    - name: Install uv
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 #v7.1.2
      with:
        version: "latest"
    
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v6
      with:
        python-version: "3.13.3"
    
    - name: Install dependencies
      run: uv sync --frozen --no-cache
    
    - name: Run pytest
      run: uv run pytest
